### ISSUE TITLE
plz fix my fav game rn

### ISSUE THREAD

**Issue by vcjds** [kuba6000/Statki#1]
![image](https://user-images.githubusercontent.com/113699457/193084880-430b104d-2a4b-4d74-95b4-56822735af42.png)
cant place last ship

**Comment by vcjds** [comment]
where fix

**Comment by vcjds** [comment]
email

**Comment by vcjds** [comment]
goes

**Comment by vcjds** [comment]
brrrrrrr

**Comment by TellingSalamander** [comment]
Skill issue
